---
galaxy_info:
  role_name: k3s
  author: egvimo
  description: Installation of K3s

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - k3s
