---
dependencies: []

galaxy_info:
  role_name: raspberry
  author: egvimo
  description: Configuration of Raspberry Pi via raspi-config

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - raspberry
