---
- include_role:
    name: helper
    tasks_from: apt_installer
  vars:
    apt_key_url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    apt_repository: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    apt_repository_name: brave-browser-release
    apt_package_name: brave-browser
