---
galaxy_info:
  role_name: docker
  author: egvimo
  description: Installation of Docker

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - ubuntu
    - docker
    - container
